### ISSUE TITLE
default helpinfo why throw and error

### ISSUE THREAD

**Issue by tienne** [vilic/clime#37]
i use default command here
~~~typescript
export const description = `
==============================
cli: v${version}
maintainer: ${author.name}
==============================
`;

export const subcommands: SubcommandDefinition[] = [
  { name: 'worker' }
];
~~~

command run but error code 1 and print helpinfo
i want helpInfo return and not throw how can?

**Comment by vilic** [comment]
@tienne Hi, it is by-design. To exit with code 0 you may specify `-h`, `--help` or `-?` explicitly.

**Comment by tienne** [comment]
aha! thanks!
this issue close
