### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by aSapien** [vilic/clime#38]
The [demo](https://vane.life/2017/11/06/write-slack-slash-commands-with-clime/) doesn't work

I carefully made sure I'm following the guide and wiring the app correctly. It doesn't work:

```bash
ERR Unknown subcommand "demo".

  USAGE

    / <subcommand>
```

**Comment by vilic** [comment]
Hi, can you check your runtime commands directory and make sure demo.js is present?

**Comment by aSapien** [comment]
Hi @vilic,

Thank you for your attention. Please put this issue on hold. 
I managed to resolve the issue by having a `default` handler and removing the `command` argument from the execution arguments:
https://github.com/aSapien/clime-slack/commit/466cfdfbf651fc8d073f70fa3ba7073799dcf805

Then, having only a `subcommands` entry in the `default.ts` handler exposes the functionality I am looking for.
