### ISSUE TITLE
StringCastable example from README not working

### ISSUE THREAD

**Issue by plu** [vilic/clime#44]
```typescript
export class File implements StringCastable<File> {
    constructor(public path: string) {}

    // This is required by the StringCastable interface, but it's never called.
    cast(source: string, context: CastingContext<File>): Promise<File> {
        console.log('This is never called');
        return new Promise(() => {});
    }

    // But this is actually called.
    static cast(source: string, context: CastingContext<File>): Promise<File> {
        console.log('This is actually called');
        return new Promise((resolve, reject) => {
            resolve(new File(Path.resolve(context.cwd, source)));
        });
    }
}
```

I'm wondering if I'm doing something wrong here: The `StringCastable` forces me to implement `cast(source: string, context: CastingContext<File>): Promise<File>`, which is then never even called. The static one is actually being called. And unless I implement the static one, I get a runtime error:

`Error: Type `File` cannot be casted from a string, see `StringCastable` interface for more information`

**Comment by vilic** [comment]
Thanks for addressing this. `StringCastable` should be the type of the constructor instead of the instance. So `implements StringCastable` should be removed from the example.

**Comment by vilic** [comment]
Fixed https://github.com/vilic/clime/commit/30e427a9765102cf3b99f3790119cf8e21e9f53d

**Comment by plu** [comment]
Thank you, this wasn't clear to me, I'm still new to TS.

I really love `clime` and the API it  provides, great work you have done here!
