### ISSUE TITLE
Run Commands support

### ISSUE THREAD

**Issue by mattyclarkson** [vilic/clime#50]
The [`rc`][rc] package provides a standard way to lookup configuration files. It would be great if `clime` had built in support for the same lookup. I am keen to implement this if you think it would be a good addition to the project. We can avoid `statSync` that `rc` does because `clime` is `async` by default so we can do the file lookups asynchronously.

If 👍 on this idea, I can do some investigation and figure out a spec before actually implementing it. I imagine it would be in [`preprocessArguments`][pa] but that's based on 1 minute or research.

[rc]: https://www.npmjs.com/package/rc
[pa]: https://github.com/vilic/clime/blob/9dbc740ed24ae2bf5e4c6682d17199a0d2650354/src/core/cli.ts#L275

**Comment by vilic** [comment]
Thanks for this suggestion! Instead of having this built-in, I think it might be better to add another `Castable` implementation outside of the core. E.g.:

```ts
export class SomeOptions extends Options {
  @option({
    flag: 'c',
    description: 'some configuration',
    // Currently a string value might be needed to trigger the casting,
    // might add another option on castable to force casting `undefined`.
    // Search `defaultValue` in `cli.ts` for details.
    default: '',
  })
  config: Config;
}
```

**Comment by mattyclarkson** [comment]
Thanks for the suggestion. Will look into it.
