### ISSUE TITLE
[code question] What's the point of "shim"

### ISSUE THREAD

**Issue by lwyj123** [vilic/clime#52]
I am learning the source code and the design of clime.  When I was studying the `shim` part, I was confused by the comment `A Clime command line interface shim for pure Node.js.`. What's the aim of the shim.

**Comment by vilic** [comment]
Hi, please check out the following links:

https://github.com/vilic/clime-slack
https://vane.life/2017/11/06/write-slack-slash-commands-with-clime/

The original goal of clime is the core of next-gen shell (still in our TODO list, but not in near future), which would be able to adapt ansi interface and GUI at the same time. Though of course currently it's kind of lame.
