### ISSUE TITLE
[Question] How implement shutdown

### ISSUE THREAD

**Issue by galkin** [vilic/clime#54]
Thank you for awesome package. Some of my command can take more than 3 minutes. Do we have best practice for shutdown the command execution?

**Comment by vilic** [comment]
Hi, are those commands synchronous or asynchronous? And who will perform the "shutdown" operation? Ctrl+C or the command itself?

**Comment by galkin** [comment]
`Ctrl+C`

**Comment by galkin** [comment]
> Hi, are those commands synchronous or asynchronous?
asynchronous with async/await
> And who will perform the "shutdown" operation?
User press `Ctrl+C`, command should graceful shutdown. For example, disconnect from DB, close file, etc.

**Comment by vilic** [comment]
I see, currently I don't think there are direct related features implemented by clime. To be honest, I don't think the `Promise` idea behind clime is suitable for describing this. RxJS might serve this purpose better though.

I think I could add a built-in shim with RxJS support in future versions, the core might need a little bit modification for types.

**Comment by galkin** [comment]
closed as clime didn't receive updates for long time
