### ISSUE TITLE
[Question] How to share variables between different command

### ISSUE THREAD

**Issue by BuBuHighLighter** [vilic/clime#55]
## Description

I'm going to save the state of user so that I can get it in different commands. But every command is a `child_process`, I have no idea to do it. Do you have any good idea?

**Comment by vilic** [comment]
What is the expected lifecycle of those variables? Will a cache/config file do in your case?

**Comment by BuBuHighLighter** [comment]
The variable keep alive until user close the window. Saving the state in a file is not very good for me. Could you please introduce the cache you mentioned for me?

**Comment by vilic** [comment]
By closing the window do you mean closing the shell window? You might want to consider environment variable. But I guess the implementation, if viable, might be shell specific. I am not aware a mechanism to detect shell window closing.

**Comment by BuBuHighLighter** [comment]
I think global variable can be satisfied with my demand, which can be get/set by different commands.
