### ISSUE TITLE
Wanted to say thank you! :heart:

### ISSUE THREAD

**Issue by dgreene1** [vilic/clime#58]
No issue here-- in fact, I'm loving using clime! I just wanted to say thank you @vilic for making this and for maintaining it.

I wish more people used it! :) I'll try to get the word out my smallish network. But again, I just wanted to send gratitude your way.

**Comment by vilic** [comment]
Hi @dgreene1, it's really great to know you like it! You guys cheer me up, and I hope I will be able to put more time on this project and even to complete the bigger picture behind Clime!
